platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!
#source 'https://github.com/CocoaPods/Specs.git'
# 镜像源
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'SwiftModulesDemo' do

  pod 'SwiftModules', :path => '../'
  
  pod 'Kingfisher'
  # git 地址下载
#  pod 'SwiftModules', :git => 'https://github.com/aichiko0225/SwiftModules'
end
